/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentation.ui.gui;

import business.model.Tabela;

/**
 *
 * @author Fábio
 */
public class DlgEditTabela extends javax.swing.JDialog {
    
    //constantes para que o seu uso seja mais intuitivo
    public final static Integer CONFIRMAR = 1;
    public final static Integer CANCELAR = 0;
    
    private Integer botaoPressionado = CONFIRMAR; //Assume que o utilizador vai confirmar as mudanças
    private Tabela tabela;
    
    private static Integer numColunas = 2; //Nº de colunas inicial
    private static Integer num = 1; //Numero inicial. Será incrementado com cada utilização
    private static boolean editar = false; //impede a incremntação do número quando estamos a editar
    private static Integer numEdicao; //guarda o codigo da tabela que estamos a editar

    /**
     * Creates new form DlgEditTabela
     */
    //Construtor para tabelas novas
    public DlgEditTabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Faz com que a janela apareça no meio do ecrã
        txtNumColunas.setText(numColunas.toString()); //Inciar txtField
        getRootPane().setDefaultButton(btnConfirmar); //Faz com que enter ative o botão Confirmar
        editar = false;
    }
    
    //Construtor para editar tabelas existentes
    public DlgEditTabela(java.awt.Frame parent, boolean modal, Tabela tabelaParaEditar) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnConfirmar);
        if(tabelaParaEditar != null){
            txtNome.setText(tabelaParaEditar.getNomeTabela());
            txtDescricao.setText(tabelaParaEditar.getDescricao());
            //Adicionar colunas --------------------------------------------------------------------
        }
        editar = true;
        numEdicao = tabelaParaEditar.getNumero();//guarda o codigo da pessoa que estamos a editar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblNumColunas = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNumColunas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        lblNomeColuna1 = new javax.swing.JLabel();
        txtColuna1 = new javax.swing.JTextField();
        lblNomeColuna2 = new javax.swing.JLabel();
        txtColuna2 = new javax.swing.JTextField();
        lblNomeColuna3 = new javax.swing.JLabel();
        txtColuna3 = new javax.swing.JTextField();
        lblNomeColuna4 = new javax.swing.JLabel();
        txtColuna4 = new javax.swing.JTextField();
        lblNomeColuna5 = new javax.swing.JLabel();
        txtColuna5 = new javax.swing.JTextField();
        lblNomeColuna6 = new javax.swing.JLabel();
        txtColuna6 = new javax.swing.JTextField();
        lblNomeColuna7 = new javax.swing.JLabel();
        txtColuna7 = new javax.swing.JTextField();
        lblNomeColuna8 = new javax.swing.JLabel();
        txtColuna8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar Tabela");
        setResizable(false);

        lblNome.setText("Nome da Tabela:");

        lblDescricao.setText("Descrição:");

        lblNumColunas.setText("Nº de Colunas:");

        txtNumColunas.setEditable(false);

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(3);
        txtDescricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescricao);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnMais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMais.setText("+");
        btnMais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMais.addActionListener(this::btnMaisActionPerformed);

        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenos.addActionListener(this::btnMenosActionPerformed);

        lblNomeColuna1.setText("Coluna 1:");

        lblNomeColuna2.setText("Coluna 2:");

        lblNomeColuna3.setText("Coluna 3:");

        txtColuna3.setEnabled(false);

        lblNomeColuna4.setText("Coluna 4:");

        txtColuna4.setEnabled(false);

        lblNomeColuna5.setText("Coluna 5:");

        txtColuna5.setEnabled(false);

        lblNomeColuna6.setText("Coluna 6:");

        txtColuna6.setEnabled(false);

        lblNomeColuna7.setText("Coluna 7:");

        txtColuna7.setEnabled(false);

        lblNomeColuna8.setText("Coluna 8:");

        txtColuna8.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescricao)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumColunas)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeColuna3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColuna3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeColuna4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColuna4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNomeColuna1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtColuna1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNomeColuna2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtColuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeColuna7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColuna7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeColuna8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColuna8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNomeColuna5)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtColuna5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNomeColuna6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtColuna6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumColunas)
                    .addComponent(txtNumColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais)
                    .addComponent(btnMenos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna1)
                            .addComponent(txtColuna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna2)
                            .addComponent(txtColuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna3)
                            .addComponent(txtColuna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna4)
                            .addComponent(txtColuna4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna5)
                            .addComponent(txtColuna5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna6)
                            .addComponent(txtColuna6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna7)
                            .addComponent(txtColuna7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeColuna8)
                            .addComponent(txtColuna8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Confirma se o utilizador quer confirmar ou cancelar 
    public int getBotaoPressionado(){
        return botaoPressionado;
    }
    
    //Retorna o novo objeto tabela
    public Tabela getTabela(){
        return tabela;
    }
    
    //Diminui o nº de colunas da nova tabela
    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        numColunas -= 1;
        txtNumColunas.setText(numColunas.toString()); //Atualiza o nº de colunas no textField
        
        switch (numColunas){
            case 1:
                txtColuna2.setText(null); //Apaga o texto
                txtColuna2.setEnabled(false); //Desativa o txtField
                btnMenos.setEnabled(false); //Desativa o butão Menos
                break;
            case 2:
                txtColuna3.setText(null);
                txtColuna3.setEnabled(false);
                break;
            case 3:
                txtColuna4.setText(null);
                txtColuna4.setEnabled(false);
                break;
            case 4:
                txtColuna5.setText(null);
                txtColuna5.setEnabled(false);
                break;
            case 5:
                txtColuna6.setText(null);
                txtColuna6.setEnabled(false);
                break;
            case 6:
                txtColuna7.setText(null);
                txtColuna7.setEnabled(false);
                break;
            case 7:
                txtColuna8.setText(null);
                txtColuna8.setEnabled(false);
                btnMais.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    //Aumenta o nº de colunas da nova tabela
    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        numColunas += 1;
        txtNumColunas.setText(numColunas.toString()); //Atualiza txtField
        
        switch (numColunas){
            case 2:
                btnMenos.setEnabled(true); //Ativa o butão menos quando há 2 colunas
                txtColuna2.setEnabled(true); //Ativa o textField 
                break;
            case 3:
                txtColuna3.setEnabled(true);
                break;
            case 4:
                txtColuna4.setEnabled(true);
                break;
            case 5:
                txtColuna5.setEnabled(true);
                break;
            case 6:
                txtColuna6.setEnabled(true);
                break;
            case 7:
                txtColuna7.setEnabled(true);
                break;
            case 8:
                txtColuna8.setEnabled(true);
                btnMais.setEnabled(false); //Desativa o butão Mais quando há 8 colunas
                break;
        }
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        botaoPressionado = CANCELAR;
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (editar == false){ //Verifica se está a adicionar uma tabela nova ou não
            //Criação da tabelas com seus dados e colunas. Colunas não usadas serão null
            tabela = new Tabela(num, txtNome.getText(), txtDescricao.getText(), numColunas, txtColuna1.getText(), txtColuna2.getText(),
            txtColuna3.getText(), txtColuna4.getText(), txtColuna5.getText(), txtColuna6.getText(), txtColuna7.getText(), txtColuna8.getText());
            botaoPressionado = CONFIRMAR;
            this.num++; //Incrementa o número
            dispose();
        }
        else{
            tabela = new Tabela(numEdicao, txtNome.getText(), txtDescricao.getText(), numColunas, txtColuna1.getText(), txtColuna2.getText(),
            txtColuna3.getText(), txtColuna4.getText(), txtColuna5.getText(), txtColuna6.getText(), txtColuna7.getText(), txtColuna8.getText());
            botaoPressionado = CONFIRMAR;
            dispose();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeColuna1;
    private javax.swing.JLabel lblNomeColuna2;
    private javax.swing.JLabel lblNomeColuna3;
    private javax.swing.JLabel lblNomeColuna4;
    private javax.swing.JLabel lblNomeColuna5;
    private javax.swing.JLabel lblNomeColuna6;
    private javax.swing.JLabel lblNomeColuna7;
    private javax.swing.JLabel lblNomeColuna8;
    private javax.swing.JLabel lblNumColunas;
    private javax.swing.JTextField txtColuna1;
    private javax.swing.JTextField txtColuna2;
    private javax.swing.JTextField txtColuna3;
    private javax.swing.JTextField txtColuna4;
    private javax.swing.JTextField txtColuna5;
    private javax.swing.JTextField txtColuna6;
    private javax.swing.JTextField txtColuna7;
    private javax.swing.JTextField txtColuna8;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumColunas;
    // End of variables declaration//GEN-END:variables
}
