/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentation.ui.gui;

import business.model.Elemento;
import business.model.Tabela;
import business.service.ElementoService;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Fábio
 */
public class DlgEditElemento extends javax.swing.JDialog {

    //constantes para que o seu uso seja mais intuitivo
    public final static Integer CONFIRMAR = 1;
    public final static Integer CANCELAR = 0;
    
    private Integer botaoPressionado = CONFIRMAR; //Assume que o utilizador vai confirmar as mudanças
    private Elemento elemento = null;
    private Tabela tabelaBase = null;
    private ElementoService elementoService = null;
    
    private Integer num = 1; //Numero inicial que é substituido pelo maior id da table se existir. Será incrementado com cada utilização
    private Boolean fav = false; //Se estiver a editar um favorito, passa a ser true

    /**
     * Creates new form DlgEditElemento
     */
    //Construtor para elementos novos
    public DlgEditElemento(java.awt.Frame parent, boolean modal, Tabela tabela, Connection ligacao) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Faz com que a janela apareça no meio do ecrã
        this.tabelaBase = tabela;
        prepararApresentacaoDaJanela(); //Passa os nomes das colunas e controla visibilidade
        getRootPane().setDefaultButton(btnConfirmar); //Faz com que enter ative o botão Confirmar

        try {
            elementoService = new ElementoService(ligacao);
            this.num = elementoService.getUltimoId(tabelaBase) + 1; //Obtem o id mais recente da bd e incrementa       
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    //Construtor para editar elementos existentes
    public DlgEditElemento(java.awt.Frame parent, boolean modal, Tabela tabela, Elemento elementoParaEditar) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Faz com que a janela apareça no meio do ecrã
        this.tabelaBase = tabela;
        prepararApresentacaoDaJanela(); //Passa os nomes das colunas e controla visibilidade
        getRootPane().setDefaultButton(btnConfirmar); //Faz com que enter ative o botão Confirmar
        
        //Configurar dados iniciais da tabela para editar
        if(elementoParaEditar != null){
            txtColuna1.setText(elementoParaEditar.getColuna1());
            txtColuna2.setText(elementoParaEditar.getColuna2());
            txtColuna3.setText(elementoParaEditar.getColuna3());
            txtColuna4.setText(elementoParaEditar.getColuna4());
            txtColuna5.setText(elementoParaEditar.getColuna5());
            txtColuna6.setText(elementoParaEditar.getColuna6());
            txtColuna7.setText(elementoParaEditar.getColuna7());
            txtColuna8.setText(elementoParaEditar.getColuna8());
        }
        this.num = elementoParaEditar.getNumero();//guarda o codigo da pessoa que estamos a editar
        this.fav = elementoParaEditar.getFavorito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblColuna1 = new javax.swing.JLabel();
        txtColuna1 = new javax.swing.JTextField();
        lblColuna2 = new javax.swing.JLabel();
        txtColuna2 = new javax.swing.JTextField();
        lblColuna3 = new javax.swing.JLabel();
        txtColuna3 = new javax.swing.JTextField();
        lblColuna4 = new javax.swing.JLabel();
        txtColuna4 = new javax.swing.JTextField();
        lblColuna5 = new javax.swing.JLabel();
        txtColuna5 = new javax.swing.JTextField();
        lblColuna6 = new javax.swing.JLabel();
        txtColuna6 = new javax.swing.JTextField();
        lblColuna7 = new javax.swing.JLabel();
        txtColuna7 = new javax.swing.JTextField();
        lblColuna8 = new javax.swing.JLabel();
        txtColuna8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblColuna1.setText("Coluna 1:");

        lblColuna2.setText("Coluna 2:");

        lblColuna3.setText("Coluna 3:");

        lblColuna4.setText("Coluna 4:");

        lblColuna5.setText("Coluna 5:");

        lblColuna6.setText("Coluna 6:");

        lblColuna7.setText("Coluna 7:");

        lblColuna8.setText("Coluna 8:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColuna6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColuna5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna7, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColuna8, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColuna1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColuna5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblColuna8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColuna8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getBotaoPressionado(){
        return botaoPressionado;
    }
    
    //Retorna o novo objeto tabela
    public Elemento getElemento(){
        return elemento;
    }
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //Criação do elementos. Colunas não usadas serão null
        elemento = new Elemento(num, txtColuna1.getText(), txtColuna2.getText(), txtColuna3.getText(), txtColuna4.getText(),
                txtColuna5.getText(), txtColuna6.getText(), txtColuna7.getText(), txtColuna8.getText(), this.fav);
        botaoPressionado = CONFIRMAR;
        dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        botaoPressionado = CANCELAR;
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void prepararApresentacaoDaJanela(){
        //Nomes das colunas
        lblColuna1.setText(tabelaBase.getColuna1());
        lblColuna2.setText(tabelaBase.getColuna2());
        lblColuna3.setText(tabelaBase.getColuna3());
        lblColuna4.setText(tabelaBase.getColuna4());
        lblColuna5.setText(tabelaBase.getColuna5());
        lblColuna6.setText(tabelaBase.getColuna6());
        lblColuna7.setText(tabelaBase.getColuna7());
        lblColuna8.setText(tabelaBase.getColuna8());
        
        //Esconder textboxes que não vão ser usadas
        Integer numColunas = tabelaBase.getNumColunas();
        switch (numColunas) {
            case 1:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                txtColuna6.setVisible(false);
                txtColuna5.setVisible(false);
                txtColuna4.setVisible(false);
                txtColuna3.setVisible(false);
                txtColuna2.setVisible(false);
                break;
            case 2:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                txtColuna6.setVisible(false);
                txtColuna5.setVisible(false);
                txtColuna4.setVisible(false);
                txtColuna3.setVisible(false);
                break;
            case 3:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                txtColuna6.setVisible(false);
                txtColuna5.setVisible(false);
                txtColuna4.setVisible(false);
                break;
            case 4:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                txtColuna6.setVisible(false);
                txtColuna5.setVisible(false);
                break;
            case 5:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                txtColuna6.setVisible(false);
                break;
            case 6:
                txtColuna8.setVisible(false);
                txtColuna7.setVisible(false);
                break;
            case 7:
                txtColuna8.setVisible(false);
                break;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblColuna1;
    private javax.swing.JLabel lblColuna2;
    private javax.swing.JLabel lblColuna3;
    private javax.swing.JLabel lblColuna4;
    private javax.swing.JLabel lblColuna5;
    private javax.swing.JLabel lblColuna6;
    private javax.swing.JLabel lblColuna7;
    private javax.swing.JLabel lblColuna8;
    private javax.swing.JTextField txtColuna1;
    private javax.swing.JTextField txtColuna2;
    private javax.swing.JTextField txtColuna3;
    private javax.swing.JTextField txtColuna4;
    private javax.swing.JTextField txtColuna5;
    private javax.swing.JTextField txtColuna6;
    private javax.swing.JTextField txtColuna7;
    private javax.swing.JTextField txtColuna8;
    // End of variables declaration//GEN-END:variables
}
