/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.ui.gui;

import business.model.ArrayListObservable;
import business.model.Tabela;
import business.model.TabelaTableModel;
import business.service.TabelaService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import share.Funcionalidades;

/**
 *
 * @author Fábio
 */
public class starter extends javax.swing.JFrame {
    
    private ArrayListObservable<Tabela> listaTabelas;
    private Connection ligacao = null;
    private TabelaService tabelaService = null;
    private Funcionalidades funcao = null;
    private boolean mostrarTodos = true; //Quando a tabela recarrega, sabe se deve mostrar todos ou só os favoritos
    
    //Dados conexão
    String baseDados = "apdz0125_08_ProjetoJava";
    String servidor = "62.28.39.135";
    String user = "apdz0125";
    String password = "123.Abc";
    String url = "jdbc:mysql://" + servidor + ":3306/" + baseDados;
    
    /**
     * Creates new form TabelaViewer
     */
    public starter() {
        
        initComponents();
        setLocationRelativeTo(null);//Janela aparece no meio do ecrã       
        conectarBaseDados();
        this.funcao = new Funcionalidades();
        btnTodos.setEnabled(false);

        //Atualizar tabela com elementos da base de dados e caracteristicas do table model
        preencherTabelaComTodos();      
        
        //Permite interação com o rato
        tblPrincipal.addMouseListener(new MouseAdapter() { 
            @Override //Duplo clique abre uma sub-tabela
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && tblPrincipal.getSelectedRow() > -1) {
                    abrir();
                }
            } 
            @Override //Right-click abre menu popup. Codigo encontrado na net
            public void mouseReleased(MouseEvent e) {
                //Selecionar row com right-click
                int row = tblPrincipal.rowAtPoint(e.getPoint());
                tblPrincipal.setRowSelectionInterval(row, row);
                //Abrir pop-up. Metodo isPopupTrigger() encontrado na net
                if (e.isPopupTrigger() && tblPrincipal.getSelectedRow() > -1) {
                    //Mostrar apenas opção relevante
                    if (listaTabelas.get(tblPrincipal.getSelectedRow()).getFavorito() == false){
                        mnuPopUpAddicionar.show(e.getComponent(), e.getX(), e.getY());
                    }else{
                        mnuPopUpRemover.show(e.getComponent(), e.getX(), e.getY());
                    }                   
                }
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPopUpAddicionar = new javax.swing.JPopupMenu();
        mnuAdicionarAosFavoritos = new javax.swing.JMenuItem();
        mnuPopUpRemover = new javax.swing.JPopupMenu();
        mnuRemoverDosFavoritos = new javax.swing.JMenuItem();
        pnlTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        pnlButoes = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        pnlTabs = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        mnuBarra = new javax.swing.JMenuBar();
        mnuMain = new javax.swing.JMenu();
        mnuEncerrarPrograma = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuAdicionarNovaTabela = new javax.swing.JMenuItem();
        mnuAbrirTabela = new javax.swing.JMenuItem();
        mnuEditarTabela = new javax.swing.JMenuItem();
        mnuApagarTabela = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuIntrucoes = new javax.swing.JMenuItem();

        mnuAdicionarAosFavoritos.setText("Adicionar aos Favoritos");
        mnuAdicionarAosFavoritos.addActionListener(this::mnuAdicionarAosFavoritosActionPerformed);
        mnuPopUpAddicionar.add(mnuAdicionarAosFavoritos);

        mnuRemoverDosFavoritos.setText("Remover dos Favoritos");
        mnuRemoverDosFavoritos.addActionListener(this::mnuRemoverDosFavoritosActionPerformed);
        mnuPopUpRemover.add(mnuRemoverDosFavoritos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOM MANAGER");
        setMinimumSize(new java.awt.Dimension(520, 300));

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrincipal);

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);

        javax.swing.GroupLayout pnlButoesLayout = new javax.swing.GroupLayout(pnlButoes);
        pnlButoes.setLayout(pnlButoesLayout);
        pnlButoesLayout.setHorizontalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlButoesLayout.setVerticalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnTodos.setText("Ver Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);

        btnFavoritos.setText("Ver Favoritos");
        btnFavoritos.addActionListener(this::btnFavoritosActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("   LISTA DE TABELAS");

        javax.swing.GroupLayout pnlTabsLayout = new javax.swing.GroupLayout(pnlTabs);
        pnlTabs.setLayout(pnlTabsLayout);
        pnlTabsLayout.setHorizontalGroup(
            pnlTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFavoritos)
                .addContainerGap())
        );
        pnlTabsLayout.setVerticalGroup(
            pnlTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
            .addGroup(pnlTabsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnFavoritos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuMain.setText("Main");

        mnuEncerrarPrograma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuEncerrarPrograma.setText("Encerrar Aplicação");
        mnuEncerrarPrograma.addActionListener(this::mnuEncerrarProgramaActionPerformed);
        mnuMain.add(mnuEncerrarPrograma);

        mnuBarra.add(mnuMain);

        mnuManage.setText("Manage");

        mnuAdicionarNovaTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        mnuAdicionarNovaTabela.setText("Criar Nova Tabela");
        mnuAdicionarNovaTabela.addActionListener(this::mnuAdicionarNovaTabelaActionPerformed);
        mnuManage.add(mnuAdicionarNovaTabela);

        mnuAbrirTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        mnuAbrirTabela.setText("Abrir Tabela");
        mnuAbrirTabela.addActionListener(this::mnuAbrirTabelaActionPerformed);
        mnuManage.add(mnuAbrirTabela);

        mnuEditarTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        mnuEditarTabela.setText("Editar Tabela");
        mnuEditarTabela.addActionListener(this::mnuEditarTabelaActionPerformed);
        mnuManage.add(mnuEditarTabela);

        mnuApagarTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        mnuApagarTabela.setText("Apagar Tabela");
        mnuApagarTabela.addActionListener(this::mnuApagarTabelaActionPerformed);
        mnuManage.add(mnuApagarTabela);

        mnuBarra.add(mnuManage);

        mnuHelp.setText("Help");

        mnuIntrucoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        mnuIntrucoes.setText("Instruções de Utilização");
        mnuIntrucoes.addActionListener(this::mnuIntrucoesActionPerformed);
        mnuHelp.add(mnuIntrucoes);

        mnuBarra.add(mnuHelp);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        adicionarTabela();
    }//GEN-LAST:event_btnAdicionarActionPerformed
        
    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        apagarTabela();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarTabela();
    }//GEN-LAST:event_btnEditarActionPerformed
       
    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        abrir();
    }//GEN-LAST:event_btnAbrirActionPerformed

    //Atualizar tabela com apenas os elementos favoritos da base de dados
    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        mostrarTodos = false;
        btnTodos.setEnabled(true);
        btnFavoritos.setEnabled(false);
        recarregarTabela();
    }//GEN-LAST:event_btnFavoritosActionPerformed

    //Atualizar tabela com elementos da base de dados
    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        mostrarTodos = true;
        btnTodos.setEnabled(false);
        btnFavoritos.setEnabled(true);
        recarregarTabela();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void mnuAdicionarAosFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdicionarAosFavoritosActionPerformed
        adicionarOuRemoverDosFavoritos();
        recarregarTabela();
        tblPrincipal.clearSelection();
    }//GEN-LAST:event_mnuAdicionarAosFavoritosActionPerformed
    
    private void mnuRemoverDosFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoverDosFavoritosActionPerformed
        adicionarOuRemoverDosFavoritos();
        recarregarTabela();
        tblPrincipal.clearSelection();
    }//GEN-LAST:event_mnuRemoverDosFavoritosActionPerformed

    private void mnuAbrirTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirTabelaActionPerformed
        abrir();
    }//GEN-LAST:event_mnuAbrirTabelaActionPerformed

    private void mnuEncerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncerrarProgramaActionPerformed
        dispose();
    }//GEN-LAST:event_mnuEncerrarProgramaActionPerformed

    private void mnuAdicionarNovaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdicionarNovaTabelaActionPerformed
        adicionarTabela();
    }//GEN-LAST:event_mnuAdicionarNovaTabelaActionPerformed

    private void mnuEditarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarTabelaActionPerformed
        editarTabela();
    }//GEN-LAST:event_mnuEditarTabelaActionPerformed

    private void mnuApagarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarTabelaActionPerformed
        apagarTabela();
    }//GEN-LAST:event_mnuApagarTabelaActionPerformed

    private void mnuIntrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIntrucoesActionPerformed
        JOptionPane.showMessageDialog(rootPane, mostarIntucoesGestaoTabelas());
    }//GEN-LAST:event_mnuIntrucoesActionPerformed

    /**
     * Abre um novo form "TabelaViewer" com base nos dados da tabela selecionada. Fecha o form atual.
     */
    private void abrir() {
        if (tblPrincipal.getSelectedRow() > -1) {
            Integer row = tblPrincipal.getSelectedRow(); //Retorna linha selecionada       
            Tabela tabela = listaTabelas.get(row); //Retorna tabela da linha selecionada
            new TabelaViewer(tabela, ligacao).setVisible(true); //Abre nova window com base na tabela selecionada
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    /**
     * Abre um JDialog para que o utilizador introduza dados e usa-os para criar um novo objeto da classe Tabela.
     * Insere essa tabela numa lista ArrayListObservable e na base de dados. Também cria uma nome table na base de
     * dados com o nome da nova tabela para armazenar futuros elementos.
     */
    private void adicionarTabela(){
        conectarBaseDados();
        
        DlgEditTabela editorTabela = new DlgEditTabela(this, true, ligacao); 
        editorTabela.setVisible(true);

        //Só será executado quando o dialog fechar
        if (editorTabela.getBotaoPressionado() == DlgEditTabela.CONFIRMAR) {
            Tabela novaTabela = editorTabela.getTabela();
            listaTabelas.add(novaTabela);

            try { //Nova row na table "tabelas" + Nova table na base de dados (para os elementos desta tabela)
                tabelaService.guardar(novaTabela); 
                tabelaService.criarTabelaSQL(novaTabela); 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }
    
    /**
     * Abre um JDialog novo com a informação do tabela selecionada. Guarda as mudanças na base de dados e na lista de elementos.
     * Se for necessário, também altera o nome da table na base de dados associada a esta tabela
     */
    private void editarTabela(){
        if (tblPrincipal.getSelectedRow() > -1) {
            int row = tblPrincipal.getSelectedRow();

            Tabela tabelaAEditar = listaTabelas.get(row);

            DlgEditTabela editorTabela = new DlgEditTabela(this, true, tabelaAEditar);
            editorTabela.setVisible(true);

            //Só será executado quando o dialog terminar
            if (editorTabela.getBotaoPressionado() == DlgEditTabela.CONFIRMAR) {
                Tabela tabelaDoEditor = editorTabela.getTabela();
                listaTabelas.set(row, tabelaDoEditor);
               
                try { //Guarda alterações da row na table "tabelas" + Atualiza o nome da table associada a esta row na base de dados
                    tabelaService.atualizarRow(tabelaDoEditor);
                    tabelaService.atualizarNomeTable(tabelaAEditar, tabelaDoEditor);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
                //Nota: Para além do nome da table, não é preciso alterar mais dados porque o
                //proximo form escreve o nome das colunas a partir do objeto tabela que recebe
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    /**
     * Remove a tabela selecionada da lista de tabelas e da base de dados. Também faz drop da table com
     * o mesmo nome na base de dados.
     */
    private void apagarTabela(){
        if (tblPrincipal.getSelectedRow() > -1) {
            
            //Pedir ao utilizador para confirmar. Continuar operação se sim.
            if (confirmarOperacao() == JOptionPane.YES_OPTION) {
                
                Tabela tabela = listaTabelas.get(tblPrincipal.getSelectedRow());
                listaTabelas.remove(tblPrincipal.getSelectedRow());

                try { //Apaga a row na table "tabelas" + Apaga a table associada na base de dados
                    tabelaService.apagarRow(tabela);
                    tabelaService.apagarTabelaSQL(tabela);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    /**
     * Envia a tabela selecionada e para o DAO, a onde a propriedade "favorito" da tabela é marcada como true ou false
     * com base no seu valor atual.
     */
    public void adicionarOuRemoverDosFavoritos(){
        if (tblPrincipal.getSelectedRow() > -1) {
            Integer row = tblPrincipal.getSelectedRow(); //Retorna linha selecionada       
            Tabela tabela = listaTabelas.get(row); //Retorna tabela da linha selecionada

            try { //Marca como favorito ou remove dos favoritos
                tabelaService = new TabelaService(ligacao);
                tabelaService.meterOuTirarFavorito(tabela);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    /**
     * Verifica as tabelas guardadas na table "tabelas" na base de dados e passa-as todas para uma lista ArrayListObservable.
     * Controi o TableModel com base nessa lista e modifica a largura das colunas visiveis.
     */
    private void preencherTabelaComTodos(){
        try { 
            tabelaService = new TabelaService(ligacao);
            listaTabelas = tabelaService.fillAll(); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        //Codigo para o table model
        TabelaTableModel TableModel = new TabelaTableModel(Tabela.class, listaTabelas);
        tblPrincipal.setModel(TableModel);
        //Modifica a largura das colunas. Metodo encontrado na net.
        tblPrincipal.getColumnModel().getColumn(0).setPreferredWidth(55);
        tblPrincipal.getColumnModel().getColumn(1).setPreferredWidth(210);
        tblPrincipal.getColumnModel().getColumn(2).setPreferredWidth(523);
    }
    
    /**
     * Verifica a coluna "favorito" de cada tabela guardada na table "tabelas" na base de dados e coloca aquelas com o valor "1" numa
     * lista ArrayListObservable. Controi o TableModel com base nessa lisra para que apenas as favoritas sejam visiveis e modifica a
     * largura das colunas visiveis da tabela.
     */
    private void preencherTabelaComFavoritos(){
        try { 
            tabelaService = new TabelaService(ligacao);
            listaTabelas = tabelaService.fillAllFavoritos(); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        //Codigo para o table model
        TabelaTableModel TableModel = new TabelaTableModel(Tabela.class, listaTabelas);
        tblPrincipal.setModel(TableModel);
        //Modifica a largura das colunas. Metodo encontrado na net.
        tblPrincipal.getColumnModel().getColumn(0).setPreferredWidth(55);
        tblPrincipal.getColumnModel().getColumn(1).setPreferredWidth(210);
        tblPrincipal.getColumnModel().getColumn(2).setPreferredWidth(523);
    }
    
    private void recarregarTabela(){
        if (this.mostrarTodos == true){
            preencherTabelaComTodos();
        } else{
            preencherTabelaComFavoritos();
        }
    }
    
    /**
     * Usa propriedades desta classe com dados de conexão para estabelecer uma conexão à base de dados
     */
    private void conectarBaseDados() {
        try {
            //Estabelecer conexão
            this.ligacao = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    /**
     * Abre um pequeno dialog para que o utilizador confirme a sua intenção antes de executar operações perigosas.
     * Codigo encontrado na net
     * @return 
     */
    private Integer confirmarOperacao(){
        //Operação encontrada na net
        return JOptionPane.showConfirmDialog(
                null,
                "Deseja mesmo continuar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );
    }
        
    /**
     * Devolve um texto formatado com instruções para as funcionalidades deste form.
     * @return
     */
    public String mostarIntucoesGestaoTabelas(){
        String texto = "Obrigado por abrir o painel de instuções.\n\n"
                + "Na barra superior, também pode encontrar os menus 'Main' e 'Manage', que permitem controlar o estado da\n"
                + "aplicação ou executar operações de gestão de tabelas, respetivamente.\n\n"
                + "Descrição das funcionalidades: -----------------------------------------------------------------     \n\n"
                + "Adicionar (Botão ou Tecla N) - Abre um painel para criar tabelas. Pode definir entre 1 e 8 colunas distintas\n"
                + "para a sua tabela com os botões '+' e '-'. Quando estiver satisfeito, pode usar o botão 'Confirmar' para\n"
                + "guardar a nova tabela ou o botão 'Cancelar' para a descartar.\n\n"
                + "Editar (Botão ou Tecla E) - Abre um painel para edição de tabelas existentes. A única característica que\n"
                + "não pode ser editada é o número de colunas.\n\n"
                + "Apagar (Botão ou Tecla D) - Descarta a tabela selecionada.\n\n"
                + "Abrir (Botão, Tecla A ou duplo-clique numa tabela) - Abre a tabela selecionada, permitindo a visualização e\n"
                + "gestão dos elementos dessa tabela. A estrutura depende daquilo que introduziu quando a criou.\n\n"
                + "Adicionar aos Favoritos (Botão direito do rato numa tabela) - Adiciona a tabela à lista de favoritos.\n\n"
                + "Remover dos Favoritos (Botão direito do rato numa tabela) - Remove a tabela da lista de favoritos.\n\n"
                + "Ver Favoritos (Botão) - Filtra a lista de tabelas para montrar apenas as que estão marcadas como favoritoas.\n\n"
                + "Ver Todos (Botão) - Revela todas as tabelas que já foram criadas.";    
        return texto;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new starter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuAbrirTabela;
    private javax.swing.JMenuItem mnuAdicionarAosFavoritos;
    private javax.swing.JMenuItem mnuAdicionarNovaTabela;
    private javax.swing.JMenuItem mnuApagarTabela;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenuItem mnuEditarTabela;
    private javax.swing.JMenuItem mnuEncerrarPrograma;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuIntrucoes;
    private javax.swing.JMenu mnuMain;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JPopupMenu mnuPopUpAddicionar;
    private javax.swing.JPopupMenu mnuPopUpRemover;
    private javax.swing.JMenuItem mnuRemoverDosFavoritos;
    private javax.swing.JPanel pnlButoes;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JPanel pnlTabs;
    private javax.swing.JTable tblPrincipal;
    // End of variables declaration//GEN-END:variables
}
