/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.ui.gui;

import business.model.ArrayListObservable;
import business.model.Tabela;
import business.model.TabelaTableModel;
import business.service.TabelaService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import share.Funcionalidades;

/**
 *
 * @author Fábio
 */
public class starter extends javax.swing.JFrame {
    
    private ArrayListObservable<Tabela> listaTabelas;
    private Connection ligacao = null;
    private TabelaService tabelaService = null;
    private Funcionalidades funcao = null;
    
    //Dados conexão
    String baseDados = "apdz0125_08_ProjetoJava";
    String servidor = "62.28.39.135";
    String user = "apdz0125";
    String password = "123.Abc";
    String url = "jdbc:mysql://" + servidor + ":3306/" + baseDados;
    
    /**
     * Creates new form TabelaViewer
     */
    public starter() {
        
        initComponents();
        setLocationRelativeTo(null);//Janela aparece no meio do ecrã       
        conectarBaseDados();
        this.funcao = new Funcionalidades();

        try { //Atualizar tabela com elementos da base de dados
            tabelaService = new TabelaService(ligacao);
            listaTabelas = tabelaService.fillAll(); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

        //Codigo para o table model
        TabelaTableModel TableModel = new TabelaTableModel(Tabela.class, listaTabelas);
        tblPrincipal.setModel(TableModel);

        //Modifica a largura das colunas. Metodo encontrado na net.
        tblPrincipal.getColumnModel().getColumn(0).setPreferredWidth(55);
        tblPrincipal.getColumnModel().getColumn(1).setPreferredWidth(250);
        tblPrincipal.getColumnModel().getColumn(2).setPreferredWidth(483);
        
        //Permite interação com o rato
        tblPrincipal.addMouseListener(new MouseAdapter() { 
            @Override
            public void mouseClicked(MouseEvent e) { //Instruções
                //Duplo clique abre uma sub-tabela
                if (e.getClickCount() == 2 && tblPrincipal.getSelectedRow() > -1) {
                    abrir();
                }
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        pnlButoes = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        mnuBarra = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuManage = new javax.swing.JMenu();
        mnuPreferences = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOM MANAGER");
        setMinimumSize(new java.awt.Dimension(407, 260));

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrincipal);

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);

        javax.swing.GroupLayout pnlButoesLayout = new javax.swing.GroupLayout(pnlButoes);
        pnlButoes.setLayout(pnlButoesLayout);
        pnlButoesLayout.setHorizontalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlButoesLayout.setVerticalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuHome.setText("Home");
        mnuBarra.add(mnuHome);

        mnuManage.setText("Manage");
        mnuBarra.add(mnuManage);

        mnuPreferences.setText("Preferences");
        mnuBarra.add(mnuPreferences);

        mnuHelp.setText("Help");
        mnuBarra.add(mnuHelp);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlButoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Adicionar novo elemento
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        conectarBaseDados();
        
        DlgEditTabela editorTabela = new DlgEditTabela(this, true, ligacao); 
        editorTabela.setVisible(true);

        //Só será executado quando o dialog fechar
        if (editorTabela.getBotaoPressionado() == DlgEditTabela.CONFIRMAR) {
            Tabela novaTabela = editorTabela.getTabela();
            listaTabelas.add(novaTabela);

            try { //Nova row na table "tabelas" + Nova table na base de dados (para os elementos desta tabela)
                tabelaService.guardar(novaTabela); 
                tabelaService.criarTabelaSQL(novaTabela); 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed
    
    //Apagar elemento
    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if(tblPrincipal.getSelectedRow() > -1){ 
            Tabela tabela = listaTabelas.get(tblPrincipal.getSelectedRow());
            listaTabelas.remove(tblPrincipal.getSelectedRow()); 
            
            try { //Apaga a row na table "tabelas" + Apaga a table associada na base de dados
                tabelaService.apagarRow(tabela); 
                tabelaService.apagarTabelaSQL(tabela); 
            }catch (Exception ex) {
                 JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }  
        }else{
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblPrincipal.getSelectedRow() > -1) {
            int row = tblPrincipal.getSelectedRow();

            Tabela tabelaAEditar = listaTabelas.get(row);

            DlgEditTabela editorTabela = new DlgEditTabela(this, true, tabelaAEditar);
            editorTabela.setVisible(true);

            //Só será executado quando o dialog terminar
            if (editorTabela.getBotaoPressionado() == DlgEditTabela.CONFIRMAR) {
                Tabela tabelaDoEditor = editorTabela.getTabela();
                listaTabelas.set(row, tabelaDoEditor);
               
                try { //Guarda alterações da row na table "tabelas" + Atualiza o nome da table associada a esta row na base de dados
                    tabelaService.atualizarRow(tabelaDoEditor);
                    tabelaService.atualizarNomeTable(tabelaAEditar, tabelaDoEditor);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
                //Nota: Para além do nome da table, não é preciso alterar mais dados porque o
                //proximo form escreve o nome das colunas a partir do objeto tabela que recebe
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void abrir() {
        if (tblPrincipal.getSelectedRow() > -1) {
            Integer row = tblPrincipal.getSelectedRow(); //Retorna linha selecionada       
            Tabela tabela = listaTabelas.get(row); //Retorna tabela da linha selecionada
            new TabelaViewer(tabela, ligacao).setVisible(true); //Abre nova window com base na tabela selecionada
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        abrir();
    }//GEN-LAST:event_btnAbrirActionPerformed

     private void conectarBaseDados() {
        try {
            //Estabelecer conexão
            this.ligacao = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new starter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuPreferences;
    private javax.swing.JPanel pnlButoes;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JTable tblPrincipal;
    // End of variables declaration//GEN-END:variables
}
