/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.ui.gui;

import business.model.ArrayListObservable;
import business.model.ElementoTableModel;
import business.model.Elemento;
import business.model.Tabela;
import business.service.ElementoService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Fábio
 */
public class TabelaViewer extends javax.swing.JFrame {
    
    private ArrayListObservable<Elemento> listaElementos;
    private Tabela tabelaBase;
    public Connection ligacao = null;
    private ElementoService elementoService = null;
    private boolean mostrarTodos = true; //Quando a tabela recarrega, sabe se deve mostrar todos ou só os favoritos

    /**
     * Creates new form TabelaViewer
     * @param tabela
     * @param ligacao
     */
    public TabelaViewer(Tabela tabela, Connection ligacao) {
        initComponents();
        setLocationRelativeTo(null);//Janela aparece no meio do ecrã
        this.ligacao = ligacao;
        this.tabelaBase = tabela; //Para saber os nomes de cada coluna
        btnTodos.setEnabled(false);
        
        lblTitulo.setText("    " + tabela.getNomeTabela().toUpperCase()); //Escrever titulo do jFrame
        this.setTitle("    " + tabela.getNomeTabela().toUpperCase());//Escrever nome da tabela na barra superior do JFrame
        
        //Atualizar tabela com elementos da base de dados
        preencherTabelaComTodos();
        

        //Permite interações com o rato na tabela. 
        tblTabelaCustom.addMouseListener(new MouseAdapter() { 
            @Override
            public void mouseClicked(MouseEvent e) {
                //Duplo clique permite editar uma tabela
                if (e.getClickCount() == 2 && tblTabelaCustom.getSelectedRow() > -1) {
                    editarElemento();
                }
            }
            @Override //Right-click abre menu popup. Codigo encontrado na net
            public void mouseReleased(MouseEvent e) {
                //Selecionar row com right-click
                int row = tblTabelaCustom.rowAtPoint(e.getPoint());
                tblTabelaCustom.setRowSelectionInterval(row, row);
                //Abrir pop-up
                if (e.isPopupTrigger() && tblTabelaCustom.getSelectedRow() > -1) {
                    //Mostrar apenas opção relevante
                    if (listaElementos.get(tblTabelaCustom.getSelectedRow()).getFavorito() == false){
                        mnuPopUpAdicionar.show(e.getComponent(), e.getX(), e.getY());
                    }else{
                        mnuPopUpRemover.show(e.getComponent(), e.getX(), e.getY());
                    }                   
                }
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPopUpAdicionar = new javax.swing.JPopupMenu();
        mnuAdicionarAosFavoritos = new javax.swing.JMenuItem();
        mnuPopUpRemover = new javax.swing.JPopupMenu();
        mnuRemoverDosFavoritos = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaCustom = new javax.swing.JTable();
        pnlButoes = new javax.swing.JPanel();
        btnApagar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        mnuBarra = new javax.swing.JMenuBar();
        mnuMain = new javax.swing.JMenu();
        mnuHomeRetornar = new javax.swing.JMenuItem();
        mnuEncerrarAplicacao = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuAdicionarElemento = new javax.swing.JMenuItem();
        mnuEditarElemento = new javax.swing.JMenuItem();
        mnuApagarElemento = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuInstrucoes = new javax.swing.JMenuItem();

        mnuAdicionarAosFavoritos.setText("Adicionar aos Favoritos");
        mnuAdicionarAosFavoritos.addActionListener(this::mnuAdicionarAosFavoritosActionPerformed);
        mnuPopUpAdicionar.add(mnuAdicionarAosFavoritos);

        mnuRemoverDosFavoritos.setText("Remover dos Favoritos");
        mnuRemoverDosFavoritos.addActionListener(this::mnuRemoverDosFavoritosActionPerformed);
        mnuPopUpRemover.add(mnuRemoverDosFavoritos);

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(407, 260));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo.setText("jLabel1");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        tblTabelaCustom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaCustom);

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnRetornar.setText("Retornar");
        btnRetornar.addActionListener(this::btnRetornarActionPerformed);

        javax.swing.GroupLayout pnlButoesLayout = new javax.swing.GroupLayout(pnlButoes);
        pnlButoes.setLayout(pnlButoesLayout);
        pnlButoesLayout.setHorizontalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButoesLayout.createSequentialGroup()
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlButoesLayout.setVerticalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRetornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnFavoritos.setText("Ver Favoritos");
        btnFavoritos.addActionListener(this::btnFavoritosActionPerformed);

        btnTodos.setText("Ver Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);

        mnuMain.setText("Main");

        mnuHomeRetornar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        mnuHomeRetornar.setText("Retornar");
        mnuHomeRetornar.addActionListener(this::mnuHomeRetornarActionPerformed);
        mnuMain.add(mnuHomeRetornar);

        mnuEncerrarAplicacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuEncerrarAplicacao.setText("Encerrar Aplicação");
        mnuEncerrarAplicacao.addActionListener(this::mnuEncerrarAplicacaoActionPerformed);
        mnuMain.add(mnuEncerrarAplicacao);

        mnuBarra.add(mnuMain);

        mnuManage.setText("Manage");

        mnuAdicionarElemento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        mnuAdicionarElemento.setText("Criar Novo Elemento");
        mnuAdicionarElemento.addActionListener(this::mnuAdicionarElementoActionPerformed);
        mnuManage.add(mnuAdicionarElemento);

        mnuEditarElemento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        mnuEditarElemento.setText("Editar Elemento");
        mnuEditarElemento.addActionListener(this::mnuEditarElementoActionPerformed);
        mnuManage.add(mnuEditarElemento);

        mnuApagarElemento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        mnuApagarElemento.setText("Apagar Elemento");
        mnuApagarElemento.addActionListener(this::mnuApagarElementoActionPerformed);
        mnuManage.add(mnuApagarElemento);

        mnuBarra.add(mnuManage);

        mnuHelp.setText("Help");

        mnuInstrucoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        mnuInstrucoes.setText("Instruções de Utilização");
        mnuInstrucoes.addActionListener(this::mnuInstrucoesActionPerformed);
        mnuHelp.add(mnuInstrucoes);

        mnuBarra.add(mnuHelp);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFavoritos)
                                .addGap(8, 8, 8)))
                        .addContainerGap())
                    .addComponent(pnlButoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFavoritos)
                        .addComponent(btnTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        adicionarElemento();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        apagarElemento();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void mnuHomeRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHomeRetornarActionPerformed
        new starter().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_mnuHomeRetornarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       editarElemento();
    }//GEN-LAST:event_btnEditarActionPerformed
 
    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        new starter().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        mostrarTodos = true;
        btnTodos.setEnabled(false);
        btnFavoritos.setEnabled(true);
        recarregarTabela();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        mostrarTodos = false;
        btnTodos.setEnabled(true);
        btnFavoritos.setEnabled(false);
        recarregarTabela();
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void mnuAdicionarAosFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdicionarAosFavoritosActionPerformed
        adicionarOuRemoverDosFavoritos();
        recarregarTabela();
        tblTabelaCustom.clearSelection();
    }//GEN-LAST:event_mnuAdicionarAosFavoritosActionPerformed

    private void mnuRemoverDosFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoverDosFavoritosActionPerformed
        adicionarOuRemoverDosFavoritos();
        recarregarTabela();
        tblTabelaCustom.clearSelection();
    }//GEN-LAST:event_mnuRemoverDosFavoritosActionPerformed

    private void mnuEncerrarAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncerrarAplicacaoActionPerformed
        dispose();
    }//GEN-LAST:event_mnuEncerrarAplicacaoActionPerformed

    private void mnuAdicionarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdicionarElementoActionPerformed
        adicionarElemento();
    }//GEN-LAST:event_mnuAdicionarElementoActionPerformed

    private void mnuEditarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarElementoActionPerformed
        editarElemento();
    }//GEN-LAST:event_mnuEditarElementoActionPerformed

    private void mnuApagarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarElementoActionPerformed
        apagarElemento();
    }//GEN-LAST:event_mnuApagarElementoActionPerformed

    private void mnuInstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInstrucoesActionPerformed
        JOptionPane.showMessageDialog(rootPane, mostarIntucoesGestaoElementos());
    }//GEN-LAST:event_mnuInstrucoesActionPerformed

    /**
     * Abre um JDialog para que o utilizador introduza dados e usa-os para criar um novo objeto da classe Elemento.
     * Insere esse elemento numa lista ArrayListObservable e na base de dados
     */
    private void adicionarElemento(){
        DlgEditElemento editorElemento = new DlgEditElemento(this, true, tabelaBase, ligacao);
        editorElemento.setVisible(true);

        //Só será executado quando o dialog fechar
        if(editorElemento.getBotaoPressionado() == DlgEditElemento.CONFIRMAR){
            Elemento novoElemento = editorElemento.getElemento();
            listaElementos.add(novoElemento);
            
            try { //Passar para a base de dados
                elementoService = new ElementoService(ligacao);
                elementoService.guardar(novoElemento, tabelaBase); //Nova row na table associada ao elemento
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }
    
    /**
     * Remove o elemento selecionado da lista de elementos e da base de dados
     */
    private void apagarElemento(){
        if(tblTabelaCustom.getSelectedRow() > -1){
            try { //Apagar da table de acordo com o index da row selecionada
                elementoService = new ElementoService(ligacao);
                Elemento elemento = listaElementos.get(tblTabelaCustom.getSelectedRow());
                elementoService.apagarRow(elemento, tabelaBase); //Apaga a row na table associada ao elemento
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            listaElementos.remove(tblTabelaCustom.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    /**
     * Abre um JDialog novo com a informação do elemento selecionado. Guarda as mudanças na base de dados e na lista de elementos.
     */
    private void editarElemento(){
         if (tblTabelaCustom.getSelectedRow() > -1) {
            int row = tblTabelaCustom.getSelectedRow();

            Elemento elementoAEditar = listaElementos.get(row);

            DlgEditElemento editorElemento = new DlgEditElemento(this, true, tabelaBase, elementoAEditar);
            editorElemento.setVisible(true);

            //Só será executado quando o dialog terminar
            if (editorElemento.getBotaoPressionado() == DlgEditElemento.CONFIRMAR) {
                Elemento elementoDoEditor = editorElemento.getElemento();
                listaElementos.set(row, elementoDoEditor);
               
                try { //Guarda alterações da row na table "tabelas"
                    elementoService.atualizar(elementoDoEditor, tabelaBase);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    private void recarregarTabela(){
        if (this.mostrarTodos == true){
            preencherTabelaComTodos();
        } else{
            preencherTabelaComFavoritos();
        }
    }
    
    /**
     * Verifica os elemento guardados nesta tabela na base de dados e coloca-os todos numa lista ArrayListObservable.
     * Controi o table model com base nessa lista e modifica a largura da primeira coluna da tabela.
     */
    private void preencherTabelaComTodos(){
        try { 
            elementoService = new ElementoService(ligacao);
            listaElementos = elementoService.fillAll(tabelaBase); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        //Codigo para o table model
        ElementoTableModel TableModel = new ElementoTableModel(Tabela.class, listaElementos, tabelaBase);
        tblTabelaCustom.setModel(TableModel); 
        
        tblTabelaCustom.getColumnModel().getColumn(0).setMaxWidth(58); //Largura da 1ª coluna
    }
    
    /**
     * Verifica a coluna "favorito" de cada elemento guardado na base de dados e coloca aqueles com o valor "1" numa
     * lista ArrayListObservable. Controi o TableModel com base nessa lisra para que apenas os favoritos sejam visiveis
     * e modifica a largura da primeira coluna da tabela.
     */
    private void preencherTabelaComFavoritos(){
        try { 
            elementoService = new ElementoService(ligacao);
            listaElementos = elementoService.fillAllFavoritos(tabelaBase); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        //Codigo para o table model
        ElementoTableModel TableModel = new ElementoTableModel(Tabela.class, listaElementos, tabelaBase);
        tblTabelaCustom.setModel(TableModel); 
        
        tblTabelaCustom.getColumnModel().getColumn(0).setMaxWidth(58); //Largura da 1ª coluna
    }
    
    /**
     * Envia o elemento selecionado e a tabela atual para o DAO, a onde a propriedade "favorito" do elemento
     * é marcada como true ou false com base no seu valor atual.
     */
    public void adicionarOuRemoverDosFavoritos(){
        if (tblTabelaCustom.getSelectedRow() > -1) {
            Integer row = tblTabelaCustom.getSelectedRow(); //linha selecionada       
            Elemento elemento = listaElementos.get(row); //elemento da linha selecionada

            try { //Marca como favorito ou remove dos favoritos
                elementoService = new ElementoService(ligacao);
                elementoService.meterOuTirarFavorito(elemento, tabelaBase);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }           
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }

    /**
     * Devolve um texto formatado com instruções para as funcionalidades deste form.
     * @return
     */
    public String mostarIntucoesGestaoElementos(){
        String texto = "Obrigado por abrir o painel de instuções.\n\n"
                + "Na barra superior, também pode encontrar os menus 'Main' e 'Manage', que permitem controlar o estado da\n"
                + "aplicação ou executar operações de gestão de elementos, respetivamente.\n\n"
                + "Descrição das funcionalidades: -----------------------------------------------------------------     \n\n"
                + "Adicionar (Botão ou Tecla N) - Abre um painel para adicionar um elemento novo à tabela atual, respeitando\n"
                + "as colunas definidas na criação da tabela. Pode usar o botão 'Confirmar' para guardar o novo elemento ou\n"
                + "o botão 'Cancelar' para o descartar.\n\n"
                + "Editar (Botão, Tecla E ou duplo-clique numa tabela) - Abre um painel para edição de elementos existentes.\n"
                + "Qualquer característica pode ser editada.\n\n"
                + "Apagar (Botão ou Tecla D) - Descarta o elemento selecionada.\n\n"
                + "Adicionar aos Favoritos (Botão direito do rato num elemento) - Adiciona o elemento à lista de favoritos.\n\n"
                + "Remover dos Favoritos (Botão direito do rato num elemento) - Remove o elemento da lista de favoritos.\n\n"
                + "Ver Favoritos (Botão) - Mostra apenas os elementos desta tabela que estão marcados como favoritos.\n\n"
                + "Ver Todos (Botão) - Revela todos os elementos que já foram criados para esta tabela.";    
        return texto;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuAdicionarAosFavoritos;
    private javax.swing.JMenuItem mnuAdicionarElemento;
    private javax.swing.JMenuItem mnuApagarElemento;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenuItem mnuEditarElemento;
    private javax.swing.JMenuItem mnuEncerrarAplicacao;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHomeRetornar;
    private javax.swing.JMenuItem mnuInstrucoes;
    private javax.swing.JMenu mnuMain;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JPopupMenu mnuPopUpAdicionar;
    private javax.swing.JPopupMenu mnuPopUpRemover;
    private javax.swing.JMenuItem mnuRemoverDosFavoritos;
    private javax.swing.JPanel pnlButoes;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblTabelaCustom;
    // End of variables declaration//GEN-END:variables
}
