/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.ui.gui;

import business.model.ArrayListObservable;
import business.model.ElementoTableModel;
import business.model.Elemento;
import business.model.Tabela;
import business.service.ElementoService;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import share.Funcionalidades;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Fábio
 */
public class TabelaViewer extends javax.swing.JFrame {
    
    private ArrayListObservable<Elemento> listaElementos;
    private Tabela tabelaBase; //Para saber os nomes de cada coluna
    public Connection ligacao = null;
    private ElementoService elementoService = null;
    private Funcionalidades funcao = null;

    /**
     * Creates new form TabelaViewer
     */
    public TabelaViewer(Tabela tabela, Connection ligacao) {
        initComponents();
        setLocationRelativeTo(null);//Janela aparece no meio do ecrã
        this.ligacao = ligacao;
        this.tabelaBase = tabela; //Para saber os nomes de cada coluna
        this.funcao = new Funcionalidades();
        
        lblTitulo.setText("    " + tabela.getNomeTabela().toUpperCase()); //Escrever titulo do jFrame
        this.setTitle("    " + tabela.getNomeTabela().toUpperCase());//Escrever nome da tabela na barra superior do JFrame
        
        try { //Atualizar tabela com elementos da base de dados
            elementoService = new ElementoService(ligacao);
            listaElementos = elementoService.fillAll(tabelaBase); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        tblTabelaCustom.getColumnModel().getColumn(0).setPreferredWidth(58); //Largura da 1ª coluna
        
        //Codigo para o table model
        ElementoTableModel TableModel = new ElementoTableModel(Tabela.class, listaElementos, tabela);
        tblTabelaCustom.setModel(TableModel);   
        
        //Permite interação com o rato
        tblTabelaCustom.addMouseListener(new MouseAdapter() { 
            @Override
            public void mouseClicked(MouseEvent e) { //Instruções
                //Duplo clique abre uma sub-tabela
                if (e.getClickCount() == 2 && tblTabelaCustom.getSelectedRow() > -1) {
                    editarElemento();
                }
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaCustom = new javax.swing.JTable();
        pnlButoes = new javax.swing.JPanel();
        btnApagar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        mnuBarra = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuHomeRetornar = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuPreferences = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(407, 260));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("jLabel1");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        tblTabelaCustom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaCustom);

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnRetornar.setText("Retornar");
        btnRetornar.addActionListener(this::btnRetornarActionPerformed);

        javax.swing.GroupLayout pnlButoesLayout = new javax.swing.GroupLayout(pnlButoes);
        pnlButoes.setLayout(pnlButoesLayout);
        pnlButoesLayout.setHorizontalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButoesLayout.createSequentialGroup()
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlButoesLayout.setVerticalGroup(
            pnlButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRetornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuHome.setText("Home");

        mnuHomeRetornar.setText("Retornar");
        mnuHomeRetornar.addActionListener(this::mnuHomeRetornarActionPerformed);
        mnuHome.add(mnuHomeRetornar);

        mnuBarra.add(mnuHome);

        mnuManage.setText("Manage");
        mnuBarra.add(mnuManage);

        mnuPreferences.setText("Preferences");
        mnuBarra.add(mnuPreferences);

        mnuHelp.setText("Help");
        mnuBarra.add(mnuHelp);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(pnlButoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        DlgEditElemento editorElemento = new DlgEditElemento(this, true, tabelaBase, ligacao);
        editorElemento.setVisible(true);

        //Só será executado quando o dialog fechar
        if(editorElemento.getBotaoPressionado() == DlgEditElemento.CONFIRMAR){
            Elemento novoElemento = editorElemento.getElemento();
            listaElementos.add(novoElemento);
            
            try { //Passar para a base de dados
                elementoService = new ElementoService(ligacao);
                elementoService.guardar(novoElemento, tabelaBase); //Nova row na table associada ao elemento
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if(tblTabelaCustom.getSelectedRow() > -1){
            try { //Apagar da table de acordo com o index da row selecionada
                elementoService = new ElementoService(ligacao);
                Elemento elemento = listaElementos.get(tblTabelaCustom.getSelectedRow());
                elementoService.apagarRow(elemento, tabelaBase); //Apaga a row na table associada ao elemento
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            listaElementos.remove(tblTabelaCustom.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void mnuHomeRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHomeRetornarActionPerformed
        funcao.retornarPaginaPrincipal(this);
    }//GEN-LAST:event_mnuHomeRetornarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       editarElemento();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void editarElemento(){
         if (tblTabelaCustom.getSelectedRow() > -1) {
            int row = tblTabelaCustom.getSelectedRow();

            Elemento elementoAEditar = listaElementos.get(row);

            DlgEditElemento editorElemento = new DlgEditElemento(this, true, tabelaBase, elementoAEditar);
            editorElemento.setVisible(true);

            //Só será executado quando o dialog terminar
            if (editorElemento.getBotaoPressionado() == DlgEditElemento.CONFIRMAR) {
                Elemento elementoDoEditor = editorElemento.getElemento();
                listaElementos.set(row, elementoDoEditor);
               
                try { //Guarda alterações da row na table "tabelas"
                    elementoService.atualizar(elementoDoEditor, tabelaBase);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não está nada selecionado.");
        }
    }
    
    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        funcao.retornarPaginaPrincipal(this);
    }//GEN-LAST:event_btnRetornarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenuItem mnuHomeRetornar;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuPreferences;
    private javax.swing.JPanel pnlButoes;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblTabelaCustom;
    // End of variables declaration//GEN-END:variables
}
